//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressLegalEntities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressLegalEntities()
        {
            this.ClientsLegalEntitiesCompanyData = new HashSet<ClientsLegalEntitiesCompanyData>();
        }
    
        public int AddressLegalEntitiesId { get; set; }
        public int StreetId { get; set; }
        public string HouseNumber { get; set; }
        public string Apartment { get; set; }
        public string Office { get; set; }


        public virtual Street Street { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientsLegalEntitiesCompanyData> ClientsLegalEntitiesCompanyData { get; set; }
    }
}
