//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsLegalEntitiesCompanyData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientsLegalEntitiesCompanyData()
        {
            this.ClientsLegalEntities = new HashSet<ClientsLegalEntities>();
            this.ClientsLegalEntitiesContactPerson = new HashSet<ClientsLegalEntitiesContactPerson>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string OGRN { get; set; }
        public Nullable<int> AddressLegalEntitiesId { get; set; }
        public Nullable<int> EmployeeCount { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual AddressLegalEntities AddressLegalEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientsLegalEntities> ClientsLegalEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientsLegalEntitiesContactPerson> ClientsLegalEntitiesContactPerson { get; set; }
    }
}
