//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsLegalEntitiesBankData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientsLegalEntitiesBankData()
        {
            this.ClientsLegalEntities = new HashSet<ClientsLegalEntities>();
        }
    
        public int BankDataId { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string BankCorrAccount { get; set; }
        public string BankBik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientsLegalEntities> ClientsLegalEntities { get; set; }
    }
}
