//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsLegalEntities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientsLegalEntities()
        {
            this.OrdersLegalEntities = new HashSet<OrdersLegalEntities>();
        }
    
        public int ClientsLegalEntitiesId { get; set; }
        public string ClientUserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BankDataId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ClientsLegalEntitiesBankData ClientsLegalEntitiesBankData { get; set; }
        public virtual ClientsLegalEntitiesCompanyData ClientsLegalEntitiesCompanyData { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersLegalEntities> OrdersLegalEntities { get; set; }
    }
}
