//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsNaturalPersons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientsNaturalPersons()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int ClientNaturalPersonsId { get; set; }
        public string ClientUserId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public byte[] ClientPhoto { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
