//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsLegalEntitiesContactPerson
    {
        public int ContactPersonId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsActive { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Middlename { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ClientsLegalEntitiesCompanyData ClientsLegalEntitiesCompanyData { get; set; }
    }
}
