//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountStatus> AccountStatus { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AddressLegalEntities> AddressLegalEntities { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<ClientsLegalEntities> ClientsLegalEntities { get; set; }
        public virtual DbSet<ClientsLegalEntitiesBankData> ClientsLegalEntitiesBankData { get; set; }
        public virtual DbSet<ClientsLegalEntitiesCompanyData> ClientsLegalEntitiesCompanyData { get; set; }
        public virtual DbSet<ClientsLegalEntitiesContactPerson> ClientsLegalEntitiesContactPerson { get; set; }
        public virtual DbSet<ClientsNaturalPersons> ClientsNaturalPersons { get; set; }
        public virtual DbSet<ClientsTypes> ClientsTypes { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<FixedOrders> FixedOrders { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersLegalEntities> OrdersLegalEntities { get; set; }
        public virtual DbSet<OrderStatus> OrderStatus { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sexes> Sexes { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<SubscriptionPeriodMonth> SubscriptionPeriodMonth { get; set; }
        public virtual DbSet<SubscriptionType> SubscriptionType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
        public virtual DbSet<UserPassportData> UserPassportData { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
