//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixedOrders()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int FixedOrderId { get; set; }
        public Nullable<int> NaturalOrderId { get; set; }
        public Nullable<int> LegalOrderId { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual OrdersLegalEntities OrdersLegalEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
