//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
