//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ClientsNaturalPersons ClientsNaturalPersons { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Subscription Subscription { get; set; }
        public virtual Users Users { get; set; }
    }
}
