//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int SubscriptionId { get; set; }
        public string SubscriptionName { get; set; }
        public Nullable<int> SubscriptionPeriodId { get; set; }
        public Nullable<int> SubscriptionTypeId { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> PriceForMonth { get; set; }
        public Nullable<decimal> PriceFull { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual SubscriptionPeriodMonth SubscriptionPeriodMonth { get; set; }
        public virtual SubscriptionType SubscriptionType { get; set; }
        public virtual Users Users { get; set; }
    }
}
