//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dickplom1.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassportData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPassportData()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int UserPassportDataId { get; set; }
        public string PassportCountry { get; set; }
        public string PassportDepartmentСode { get; set; }
        public string PassportPlaceOfBirth { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string PassportNumber { get; set; }
        public string PassportSeries { get; set; }
        public Nullable<System.DateTime> PassportDateOfIssue { get; set; }
        public string PassportIssued { get; set; }
        public Nullable<int> SexId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Sexes Sexes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
